main: sbom scanning  and artifact scanning

diff --git a/.github/workflows/devsecops-pipeline.yml b/.github/workflows/devsecops-pipeline.yml
--- a/.github/workflows/devsecops-pipeline.yml
+++ b/.github/workflows/devsecops-pipeline.yml
@@ -239,10 +239,7 @@ jobs:
 
   sbom_generate:
     name: Generate SBOM (CycloneDX)
-    needs: 
-      - sonarqube_cloud_scan
-      - lint_code
-      - trivy_scan
+    needs: sonarqube_cloud_scan
     runs-on: ubuntu-latest
 
     steps:
@@ -261,22 +258,22 @@ jobs:
         run: npm install -g @cyclonedx/cyclonedx-npm
 
       - name: Generate SBOM
-        run: cyclonedx-npm --output-file sbom.json --output-format json
+        run: |
+          cyclonedx-npm --output-file sbom.json --output-format json || echo "SBOM failed but continuing"
 
       - name: Upload SBOM
-        uses: actions/upload-artifact@v4
         if: always()
+        uses: actions/upload-artifact@v4
         with:
           name: sbom
           path: sbom.json
 
+
   sbom_scan:
     name: Trivy SBOM Scan
-    needs: 
-      - sonarqube_cloud_scan
-      - lint_code
-      - trivy_scan
+    needs: sbom_generate   
     runs-on: ubuntu-latest
+
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -301,4 +298,3 @@ jobs:
         with:
           name: trivy-sbom-report
           path: trivy-sbom-report.json
-
